{{- if .Values.security.networkPolicies.enabled }}
{{/*
Default network policy for the platform namespace
*/}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-default-deny
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  # Default deny all - specific policies will override this
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-allow-dns
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution for all pods
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-allow-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: code-server
  policyTypes:
  - Ingress
  ingress:
  # Allow ingress from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.codeServer.service.targetPort }}
  # Allow monitoring scraping
  {{- if .Values.monitoring.prometheus.enabled }}
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: {{ .Values.monitoring.prometheus.port }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-allow-egress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: code-server
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS for package downloads and git operations
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP for package downloads
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow SSH for git operations
  - to: []
    ports:
    - protocol: TCP
      port: 22
{{- end }}