{{- if .Values.security.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vibecode-platform.rbacName" . }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vibecode-platform.rbacName" . }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vibecode-platform.rbacName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vibecode-platform.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
---
# Role for user workspace management
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vibecode-platform.rbacName" . }}-workspace
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vibecode-platform.rbacName" . }}-workspace
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vibecode-platform.rbacName" . }}-workspace
subjects:
- kind: ServiceAccount
  name: {{ include "vibecode-platform.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}