apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibecode-platform.secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
type: Opaque
data:
  # Default password for code-server instances
  password: {{ "vibecode-default" | b64enc | quote }}

  # AI API keys (these should be provided via external secret management)
  {{- if .Values.aiIntegration.openRouter.enabled }}
  openrouter-api-key: {{ "" | b64enc | quote }}
  {{- end }}

  {{- if .Values.aiIntegration.artificialAnalysis.enabled }}
  artificial-analysis-api-key: {{ "" | b64enc | quote }}
  {{- end }}

  # Database connection string for user management
  database-url: {{ "postgresql://vibecode:vibecode@postgres:5432/vibecode" | b64enc | quote }}

  # JWT secret for session management
  jwt-secret: {{ "your-jwt-secret-change-in-production" | b64enc | quote }}

  # OAuth secrets (populate these with actual values)
  github-client-id: {{ "" | b64enc | quote }}
  github-client-secret: {{ "" | b64enc | quote }}
  google-client-id: {{ "" | b64enc | quote }}
  google-client-secret: {{ "" | b64enc | quote }}
---
{{- if .Values.aiIntegration.openRouter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aiIntegration.openRouter.secretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-integration
type: Opaque
data:
  api-key: {{ "" | b64enc | quote }}
{{- end }}
---
{{- if .Values.aiIntegration.artificialAnalysis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aiIntegration.artificialAnalysis.secretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai-integration
type: Opaque
data:
  api-key: {{ "" | b64enc | quote }}
{{- end }}
