datadog:
  site: "datadoghq.com"
  # SECURITY: API key now sourced from Kubernetes secret
  apiKeyExistingSecret: "datadog-secret"
  clusterAgent:
    enabled: true
    # SECURITY: Token now sourced from Kubernetes secret
    tokenExistingSecret: "datadog-cluster-agent-secret"
    env:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: datadog-secret
            key: api-key
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secret
          key: api-key
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
  otelCollector:
    enabled: true
    ports:
      - containerPort: 4317
        hostPort: 4317
        name: "otel-grpc"
      - containerPort: 4318
        hostPort: 4318
        name: "otel-http"
  tags:
    - "env:dev"
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
            ruby: "2"
  logs:
    enabled: true
    containerCollectAll: true
  asm:
    threats:
      enabled: false
  securityAgent:
    runtime:
      enabled: false
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: false
  processAgent:
    processCollection: true
  systemProbe:
    enabled: false
