datadog:
  site: "datadoghq.com"
  # SECURITY: API key now sourced from Kubernetes secret
  apiKeyExistingSecret: "datadog-secret"
  clusterAgent:
    enabled: true
    # SECURITY: Token now sourced from Kubernetes secret
    tokenExistingSecret: "datadog-cluster-agent-secret"
    env:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: datadog-secret
            key: api-key
  # Environment variables for Datadog agent
  env:
    # Core Datadog settings
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secret
          key: api-key
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DD_KUBELET_TLS_VERIFY
      value: "false"
    # DBM and APM settings
    - name: DD_DBM_PROPAGATION_MODE
      value: "full"
    - name: DD_SERVICE
      value: "vibecode-webgui"
    - name: DD_ENV
      value: "production"
    - name: DD_VERSION
      value: "1.0.0"
    - name: DD_DBM_TRACE_INJECTION
      value: "true"
    - name: DD_TRACE_SAMPLE_RATE
      value: "1.0"
    - name: DD_TRACE_RATE_LIMIT
      value: "100"

  otelCollector:
    enabled: true
    ports:
      - containerPort: 4317
        hostPort: 4317
        name: "otel-grpc"
      - containerPort: 4318
        hostPort: 4318
        name: "otel-http"
  tags:
    - "env:production"
    - "service:vibecode-webgui"
    - "application:vibecode-platform"
    - "version:1.0.0"
    - "team:platform"
    - "tier:database"
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
            ruby: "2"
  # Database Monitoring Configuration
  processAgent:
    enabled: true
    processCollection: true
  databaseMonitoring:
    enabled: true
    postgres:
      enabled: true
      instances:
        - dbm: true
          host: postgres.vibecode.svc.cluster.local
          port: 5432
          username: datadog
          password: ${DATADOG_DB_PASSWORD}
          dbname: vibecode
          ssl: false
          tags:
            - "env:production"
            - "service:vibecode-webgui"
            - "application:vibecode-platform"
            - "version:1.0.0"

  logs:
    enabled: true
    containerCollectAll: true
  asm:
    threats:
      enabled: false
  securityAgent:
    runtime:
      enabled: false
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true
  systemProbe:
    enabled: false
