FROM node:20-alpine

WORKDIR /app

ENV DD_IAST_ENABLED=true

# Copy package files
COPY package*.json ./
COPY *.config.* ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY src/ ./src/
COPY public/ ./public/
COPY prisma/ ./prisma/
COPY .env.example ./.env

# Build the application
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]