# Fly.io configuration for VibeCode WebGUI
app = "vibecode-webgui"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NEXT_TELEMETRY_DISABLED = "1"
  DD_ENV = "production"
  DD_SERVICE = "vibecode-webgui"
  DD_VERSION = "1.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/api/monitoring/health"
    protocol = "http"
    tls_skip_verify = false

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["code-server"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[metrics]
  port = 9091
  path = "/metrics"

[[processes]]
  app = "web"
  source = "."

[[processes]]
  app = "code-server"
  source = "./docker/code-server"

# Database configuration (PostgreSQL)
[[statics]]
  guest_path = "/data"
  url_prefix = "/static"

[deploy]
  release_command = "npm run db:migrate"
  strategy = "bluegreen"

[mounts]
  source = "data"
  destination = "/data"

# Environment-specific machines
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 1024
  processes = ["code-server"]
