# Default values for vibecode-docs
# This is a YAML-formatted file.

# Image configuration
image:
  repository: ghcr.io/vibecode/docs
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: []

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/gzip-level: "6"
    nginx.ingress.kubernetes.io/enable-brotli: "true"
  hosts:
    - host: docs.vibecode.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: vibecode-docs-tls
      hosts:
        - docs.vibecode.dev

# Deployment configuration
deployment:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  
  # Container configuration
  container:
    port: 8080
    env: []
    
  # Resource limits
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  
  # Health checks
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

  # Security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001
    capabilities:
      drop:
        - ALL

  # Pod security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1001
    fsGroup: 1001

  # Node selector and tolerations
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30

# Pod Disruption Budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Service Account
serviceAccount:
  create: false
  annotations: {}
  name: ""

# Network Policy
networkPolicy:
  enabled: false
  ingress: []
  egress: []

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    scrape: true
    port: 8080
    path: /metrics
  datadog:
    enabled: true
    tags:
      - "service:vibecode-docs"
      - "component:documentation"
      - "tier:frontend"

# Additional labels and annotations
labels: {}
annotations: {}

# Environment-specific overrides
environment: production

# Volume configuration
volumes: []
volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: var-cache
    mountPath: /var/cache/nginx
  - name: var-run
    mountPath: /var/run

# Default volumes for security
defaultVolumes:
  - name: tmp
    emptyDir: {}
  - name: var-cache
    emptyDir: {}
  - name: var-run
    emptyDir: {}