# Datadog Helm Chart Values for Kubernetes Autoscaling
datadog:
  apiKeyExistingSecret: "datadog-secret"
  appKey: ""  # Add your app key here if available
  site: "datadoghq.com"
  clusterName: "vibecode-kind-test"

  env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

  # Enable Kubernetes Autoscaling (GA 2025)
  autoscaling:
    workload:
      enabled: true

  # Enhanced Kubernetes Events
  kubernetesEvents:
    unbundleEvents: true

  # Core monitoring features
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  processAgent:
    enabled: true

  # Network monitoring
  networkMonitoring:
    enabled: true

  # Security Agent
  securityAgent:
    runtime:
      enabled: true

  # System Probe features
  systemProbe:
    enableTCPQueueLength: true
    enableOOMKill: true

  # Orchestrator Explorer (Required for Pod collection)
  orchestratorExplorer:
    enabled: true

# Cluster Agent Configuration (Required version >=1.18.0)
clusterAgent:
  enabled: true
  image:
    tag: "1.24.0"  # Ensure we meet minimum version requirement
  
  # Enable custom metrics for autoscaling
  metricsProvider:
    enabled: true
    useDatadogMetrics: true

  # Additional RBAC for DatadogMetric CRD
  rbac:
    create: true

  # Autoscaling configuration
  autoscaling:
    workload:
      enabled: true
  
  # Orchestrator Explorer (Required for Pod collection)
  orchestratorExplorer:
    enabled: true

# Node Agent Configuration (Required version >=7.33.0)
agents:
  enabled: true
  image:
    tag: "7.66.1"  # Meets minimum version requirement
  
  # Orchestrator Explorer for Pod collection
  orchestratorExplorer:
    enabled: true

# Target Allocator for advanced metrics
targetAllocator:
  enabled: false
