apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
rules:
# Core Kubernetes resources
- apiGroups: [""]
  resources:
  - services
  - events
  - endpoints
  - pods
  - pods/log
  - nodes
  - nodes/metrics
  - nodes/spec
  - nodes/proxy
  - nodes/stats
  - componentstatuses
  - namespaces
  - configmaps
  - secrets
  verbs: ["get", "list", "watch"]

# Apps resources
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch"]

# Extensions
- apiGroups: ["extensions"]
  resources:
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]

# Batch jobs
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]

# Autoscaling
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]

# Policy
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "watch"]

# Networking
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  verbs: ["get", "list", "watch"]

# Storage
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  - persistentvolumes
  - persistentvolumeclaims
  verbs: ["get", "list", "watch"]

# Metrics
- nonResourceURLs: ["/metrics", "/healthz", "/readyz", "/livez"]
  verbs: ["get"]

# ConfigMaps updates for leader election
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update", "create", "list", "watch"]

# For collecting kubelet metrics
- apiGroups: [""]
  resources: ["nodes/metrics", "nodes/spec", "nodes/proxy", "nodes/stats"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
- kind: ServiceAccount
  name: datadog-agent
  namespace: datadog

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: datadog
  
---
# Additional Role for configmaps in datadog namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datadog-agent
  namespace: datadog
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datadog-agent
  namespace: datadog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datadog-agent
subjects:
- kind: ServiceAccount
  name: datadog-agent
  namespace: datadog