datadog:
  site: "datadoghq.com"
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  clusterName: "vibecode-prod-aks-84859296"
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
  processAgent:
    enabled: true
  networkMonitoring:
    enabled: true
  databaseMonitoring:
    enabled: true
  env:
    - name: DD_LLMOBS_ENABLED
      value: "1"
    - name: DD_LLMOBS_AGENTLESS_ENABLED
      value: "1"
    - name: DD_LLMOBS_ML_APP
      value: "vibecode-ai"
    - name: DD_SERVICE
      value: "vibecode-webgui"
    - name: DD_ENV
      value: "production"

agents:
  image:
    tag: "7.66.1"
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  useHostNetwork: false

clusterAgent:
  enabled: true
  replicas: 2
  metricsProvider:
    enabled: true
    useDatadogMetrics: true
  rbac:
    create: true
  admissionController:
    enabled: true

clusterChecksRunner:
  enabled: true

orchestratorExplorer:
  enabled: true

networkMonitoring:
  enabled: true

securityAgent:
  runtime:
    enabled: true

systemProbe:
  enableTCPQueueLength: true
  enableOOMKill: true

