---
apiVersion: v1
kind: Namespace
metadata:
  name: vibecode-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-config
  namespace: vibecode-test
data:
  DATABASE_URL: "postgresql://vibecode:vibecode_password@postgres-service.vibecode:5432/vibecode"
  REDIS_URL: "redis://redis-service.vibecode:6379"
  NEXTAUTH_URL: "http://localhost:3000"
  NODE_ENV: "production"
  DD_SITE: "datadoghq.com"
  DD_SERVICE: "vibecode-health-check"
  DD_VERSION: "1.0.0"
  DD_ENV: "kind-test"
---
apiVersion: v1
kind: Secret
metadata:
  name: health-check-secrets
  namespace: vibecode-test
type: Opaque
stringData:
  NEXTAUTH_SECRET: "test-jwt-secret-for-health-check-testing"
  DATADOG_API_KEY: "placeholder-set-real-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
  namespace: vibecode-test
  labels:
    app: health-check-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check-service
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      containers:
      - name: health-check
        image: node:18-alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Health check service running...'; sleep 30; done"]
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: REDIS_URL
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: NEXTAUTH_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: NODE_ENV
        - name: DD_SITE
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: DD_SITE
        - name: DD_SERVICE
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: DD_SERVICE
        - name: DD_VERSION
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: DD_VERSION
        - name: DD_ENV
          valueFrom:
            configMapKeyRef:
              name: health-check-config
              key: DD_ENV
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: health-check-secrets
              key: NEXTAUTH_SECRET
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: health-check-secrets
              key: DATADOG_API_KEY
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Health check OK'"
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Ready'"
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: vibecode-test
spec:
  selector:
    app: health-check-service
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP