---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  namespace: vibecode-platform
data:
  valkey.conf: |
    # Valkey configuration for VibeCode Platform
    # Redis-compatible configuration
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    tcp-keepalive 300
    timeout 0
    databases 16
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-pvc
  namespace: vibecode-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: vibecode-platform
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:7-alpine
        ports:
        - containerPort: 6379
        command:
          - valkey-server
          - /etc/valkey/valkey.conf
        volumeMounts:
        - name: valkey-data
          mountPath: /data
        - name: valkey-config
          mountPath: /etc/valkey
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: valkey-data
        persistentVolumeClaim:
          claimName: valkey-pvc
      - name: valkey-config
        configMap:
          name: valkey-config
          
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
  namespace: vibecode-platform
  labels:
    app: valkey
spec:
  selector:
    app: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP