---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vibecode-config
  namespace: vibecode
data:
  DATABASE_URL: "postgresql://vibecode:vibecode_password@postgres-service:5432/vibecode"
  REDIS_URL: "redis://redis-service:6379"
  NEXTAUTH_URL: "http://localhost:3000"
  NODE_ENV: "production"
  DD_SITE: "datadoghq.com"
  DD_SERVICE: "vibecode-webgui"
  DD_VERSION: "1.0.0"
  DD_ENV: "kind-test"
---
apiVersion: v1
kind: Secret
metadata:
  name: vibecode-secrets
  namespace: vibecode
type: Opaque
data:
  # SECURITY: Secrets now sourced from separate script or Kubernetes secrets
  # DO NOT commit actual secrets - use environment variables or secret management
  NEXTAUTH_SECRET: REPLACE_WITH_BASE64_ENCODED_NEXTAUTH_SECRET
  DD_API_KEY: REPLACE_WITH_BASE64_ENCODED_DATADOG_API_KEY
  DD_APP_KEY: REPLACE_WITH_BASE64_ENCODED_DATADOG_APP_KEY
  NEXT_PUBLIC_DD_RUM_APPLICATION_ID: REPLACE_WITH_BASE64_ENCODED_RUM_APP_ID
  NEXT_PUBLIC_DD_RUM_CLIENT_TOKEN: REPLACE_WITH_BASE64_ENCODED_RUM_CLIENT_TOKEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibecode-webgui
  namespace: vibecode
  labels:
    app: vibecode-webgui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vibecode-webgui
  template:
    metadata:
      labels:
        app: vibecode-webgui
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command:
          - sh
          - -c
          - |
            until pg_isready -h postgres-service -p 5432 -U vibecode; do
              echo "Waiting for PostgreSQL..."
              sleep 2
            done
            echo "PostgreSQL is ready!"
      - name: wait-for-redis
        image: redis:7-alpine
        command:
          - sh
          - -c
          - |
            until redis-cli -h redis-service -p 6379 ping; do
              echo "Waiting for Redis..."
              sleep 2
            done
            echo "Redis is ready!"
      containers:
      - name: vibecode-webgui
        image: node:20-alpine
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: REDIS_URL
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: NEXTAUTH_URL
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: NODE_ENV
        - name: DD_SITE
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: DD_SITE
        - name: DD_SERVICE
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: DD_SERVICE
        - name: DD_VERSION
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: DD_VERSION
        - name: DD_ENV
          valueFrom:
            configMapKeyRef:
              name: vibecode-config
              key: DD_ENV
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: vibecode-secrets
              key: NEXTAUTH_SECRET
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: vibecode-secrets
              key: DD_API_KEY
        - name: DD_APP_KEY
          valueFrom:
            secretKeyRef:
              name: vibecode-secrets
              key: DD_APP_KEY
        - name: NEXT_PUBLIC_DD_RUM_APPLICATION_ID
          valueFrom:
            secretKeyRef:
              name: vibecode-secrets
              key: NEXT_PUBLIC_DD_RUM_APPLICATION_ID
        - name: NEXT_PUBLIC_DD_RUM_CLIENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vibecode-secrets
              key: NEXT_PUBLIC_DD_RUM_CLIENT_TOKEN
        command:
          - sh
          - -c
          - |
            # Install dependencies and run the application
            npm install -g npm@latest
            npm ci --only=production
            npm run build
            npm start
        workingDir: /app
        volumeMounts:
        - name: app-source
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /api/monitoring/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/monitoring/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: app-source
        hostPath:
          path: /Users/ryan.maclean/vibecode-webgui
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: vibecode-service
  namespace: vibecode
spec:
  selector:
    app: vibecode-webgui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort