# Authelia Configuration for VibeCode Platform
# Simplified configuration for development

apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: vibecode-auth
data:
  configuration.yml: |
    # Server configuration
    server:
      host: 0.0.0.0
      port: 9091
      
    # Logging configuration
    log:
      level: info
      format: text
      
    # Identity validation configuration
    identity_validation:
      reset_password:
        jwt_secret: "REPLACE_WITH_SECURE_JWT_SECRET"
    
    # Time-based One-Time Password configuration
    totp:
      issuer: VibeCode
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1
      secret_size: 32
    
    # WebAuthn configuration for hardware keys
    webauthn:
      timeout: 60s
      display_name: VibeCode Development Platform
      attestation_conveyance_preference: indirect
      user_verification: preferred
      
    # Authentication backend
    authentication_backend:
      password_reset:
        disable: false
      refresh_interval: 5m
      
      # File-based user database for development
      file:
        path: /config/users_database.yml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
          
    # Access control configuration
    access_control:
      default_policy: deny
      networks:
        - name: internal
          networks:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      rules:
        # Allow access to Authelia itself
        - domain: auth.localhost
          policy: bypass
          
        # User workspaces - requires user group with 2FA
        - domain: "*.localhost"
          policy: two_factor
          subject: ["group:users", "group:developers"]
    
    # Session configuration
    session:
      name: authelia_session
      secret: "REPLACE_WITH_SECURE_SESSION_SECRET"
      expiration: 1h
      inactivity: 5m
      remember_me: 1M
      cookies:
        - domain: auth.localhost
          same_site: lax
          authelia_url: "https://auth.localhost:8090"
      
    # Regulation (rate limiting)
    regulation:
      max_retries: 3
      find_time: 10m
      ban_time: 12h
      
    # Storage configuration - use local storage for simplicity
    storage:
      encryption_key: "vibecode-storage-encryption-key-change-in-production"
      local:
        path: /config/db.sqlite3
        
    # Notification configuration
    notifier:
      disable_startup_check: true
      filesystem:
        filename: /config/notification.txt
---
# Users database for file-based authentication
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: vibecode-auth
type: Opaque
stringData:
  users_database.yml: |
    users:
      admin:
        disabled: false
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$QVlVSUFXUWpBa3VUU1JvZkV6YWJ5ZA$G4jup3aYRNzHHIbXJvjT5jAZcXQlLJGnbPvE8VQqOhk"
        email: admin@vibecode.dev
        groups:
          - admins
          - users
          
      developer:
        disabled: false
        displayname: "Developer"
        password: "$argon2id$v=19$m=65536,t=3,p=4$QVlVSUFXUWpBa3VUU1JvZkV6YWJ5ZA$G4jup3aYRNzHHIbXJvjT5jAZcXQlLJGnbPvE8VQqOhk"
        email: dev@vibecode.dev
        groups:
          - users
          - developers
          
      user:
        disabled: false
        displayname: "Regular User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$QVlVSUFXUWpBa3VUU1JvZkV6YWJ5ZA$G4jup3aYRNzHHIbXJvjT5jAZcXQlLJGnbPvE8VQqOhk"
        email: user@vibecode.dev
        groups:
          - users