# Authelia Configuration for VibeCode Platform
# Enterprise-grade authentication with 2FA/SSO support

apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: vibecode-auth
data:
  configuration.yml: |
    # Server configuration
    server:
      address: "tcp://0.0.0.0:9091/"
      
    # Logging configuration
    log:
      level: info
      format: text
      
    # Identity validation configuration
    identity_validation:
      reset_password:
        jwt_secret: "vibecode-jwt-secret-change-in-production"
    
    # Time-based One-Time Password configuration
    totp:
      issuer: VibeCode
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1
      secret_size: 32
    
    # WebAuthn configuration for hardware keys
    webauthn:
      timeout: 60s
      display_name: VibeCode Development Platform
      attestation_conveyance_preference: indirect
      user_verification: preferred
      
    # Authentication backend
    authentication_backend:
      password_reset:
        disable: false
      refresh_interval: 5m
      
      # File-based user database for development
      file:
        path: /config/users_database.yml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 64
          
    # Access control configuration
    access_control:
      default_policy: deny
      networks:
        - name: internal
          networks:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      rules:
        # Allow access to Authelia itself
        - domain: auth.localhost
          policy: bypass
          
        # Admin access - requires admin group
        - domain: admin.localhost
          policy: two_factor
          subject: ["group:admins"]
          
        # User workspaces - requires user group with 2FA
        - domain: "*.localhost"
          policy: two_factor
          subject: ["group:users", "group:developers"]
          
        # Public documentation
        - domain: docs.localhost
          policy: bypass
          
        # API endpoints - require API access group
        - domain: api.localhost
          policy: one_factor
          subject: ["group:api-users"]
          resources:
            - "^/api/.*$"
    
    # Session configuration
    session:
      name: authelia_session
      cookies:
        - domain: localhost
          same_site: lax
          authelia_url: "https://auth.localhost:8090"
          default_redirection_url: "https://auth.localhost:8090"
      secret: "vibecode-session-secret-change-in-production"
      expiration: 1h
      inactivity: 5m
      remember_me: 1M
      
      # Redis session storage
      redis:
        host: redis.vibecode-storage.svc.cluster.local
        port: 6379
        database_index: 0
        maximum_active_connections: 8
        minimum_idle_connections: 0
      
    # Regulation (rate limiting)
    regulation:
      max_retries: 3
      find_time: 10m
      ban_time: 12h
      
    # Storage configuration
    storage:
      encryption_key: "vibecode-storage-encryption-key-change-in-production"
      postgres:
        host: postgres.vibecode-storage.svc.cluster.local
        port: 5432
        database: authelia
        schema: public
        username: authelia
        password: "authelia-db-password"
        timeout: 5s
        
    # Notification configuration
    notifier:
      disable_startup_check: true
      filesystem:
        filename: /config/notification.txt
---
# Users database for file-based authentication
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: vibecode-auth
type: Opaque
stringData:
  users_database.yml: |
    users:
      admin:
        disabled: false
        displayname: "Admin User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$QVlVSUFXUWpBa3VUU1JvZkV6YWJ5ZA$G4jup3aYRNzHHIbXJvjT5jAZcXQlLJGnbPvE8VQqOhk"
        email: admin@vibecode.dev
        groups:
          - admins
          - users
          
      developer:
        disabled: false
        displayname: "Developer"
        password: "$argon2id$v=19$m=65536,t=3,p=4$QVlVSUFXUWpBa3VUU1JvZkV6YWJ5ZA$G4jup3aYRNzHHIbXJvjT5jAZcXQlLJGnbPvE8VQqOhk"
        email: dev@vibecode.dev
        groups:
          - users
          - developers
          
      user:
        disabled: false
        displayname: "Regular User"
        password: "$argon2id$v=19$m=65536,t=3,p=4$QVlVSUFXUWpBa3VUU1JvZkV6YWJ5ZA$G4jup3aYRNzHHIbXJvjT5jAZcXQlLJGnbPvE8VQqOhk"
        email: user@vibecode.dev
        groups:
          - users