#!/usr/bin/env python3

# -- VibeCode Telemetry --
import sys
import os
try:
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))
    from vibecode.telemetry import init_telemetry
    tracer = init_telemetry(os.path.basename(__file__))
except ImportError:
    pass
# ------------------------

"""
GitHub integration for offline cloud infrastructure testing.
Updates GitHub issues with test results and creates automated reports.
"""

import subprocess
import json
import os
from pathlib import Path
from datetime import datetime


class GitHubIntegration:
    """GitHub integration for offline testing results."""
    
    def __init__(self):
        self.project_root = Path(__file__).parent.parent.parent
        self.test_results = {}
        
    def run_offline_tests(self):
        """Run all offline tests and collect results."""
        print("🧪 Running offline cloud infrastructure tests...")
        
        # Test AWS configuration
        aws_result = self._run_test_suite("test_aws_cloud_deployment.py")
        self.test_results["aws"] = aws_result
        
        # Test GCP configuration
        gcp_result = self._run_test_suite("test_gcp_cloud_deployment.py")
        self.test_results["gcp"] = gcp_result
        
        # Test security validation
        security_result = self._run_test_suite("test_security_validation.py")
        self.test_results["security"] = security_result
        
        return self.test_results
    
    def _run_test_suite(self, test_file):
        """Run a specific test suite and return results."""
        test_path = self.project_root / "tests" / "tofu" / test_file
        
        try:
            result = subprocess.run(
                ["python3", "-m", "unittest", str(test_path), "-v"],
                capture_output=True,
                text=True,
                cwd=self.project_root / "tests" / "tofu",
                timeout=300
            )
            
            return {
                "success": result.returncode == 0,
                "stdout": result.stdout,
                "stderr": result.stderr,
                "returncode": result.returncode
            }
        except subprocess.TimeoutExpired:
            return {
                "success": False,
                "stdout": "",
                "stderr": "Test suite timed out",
                "returncode": -1
            }
        except Exception as e:
            return {
                "success": False,
                "stdout": "",
                "stderr": str(e),
                "returncode": -1
            }
    
    def generate_test_report(self):
        """Generate a comprehensive test report."""
        report = {
            "timestamp": datetime.now().isoformat(),
            "test_results": self.test_results,
            "summary": self._generate_summary()
        }
        
        # Save report to file
        report_file = self.project_root / "tests" / "tofu" / "test-report.json"
        with open(report_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        return report
    
    def _generate_summary(self):
        """Generate test summary."""
        total_tests = len(self.test_results)
        passed_tests = sum(1 for result in self.test_results.values() if result["success"])
        failed_tests = total_tests - passed_tests
        
        return {
            "total_tests": total_tests,
            "passed": passed_tests,
            "failed": failed_tests,
            "success_rate": (passed_tests / total_tests * 100) if total_tests > 0 else 0
        }
    
    def update_github_issue(self, issue_number, test_report):
        """Update a GitHub issue with test results."""
        summary = test_report["summary"]
        
        comment_body = f"""## 🧪 Offline Cloud Infrastructure Test Results

**Test Summary:**
- ✅ Passed: {summary['passed']}/{summary['total_tests']} tests
- ❌ Failed: {summary['failed']}/{summary['total_tests']} tests
- 📊 Success Rate: {summary['success_rate']:.1f}%

**Test Details:**
"""
        
        for platform, result in test_report["test_results"].items():
            status = "✅ PASS" if result["success"] else "❌ FAIL"
            comment_body += f"- **{platform.upper()}**: {status}\n"
        
        comment_body += f"""
**Timestamp:** {test_report['timestamp']}

**Next Steps:**
- Review failed tests and fix configuration issues
- Re-run tests after fixes
- Deploy to cloud environments once all tests pass

---
*This report was generated by the offline cloud infrastructure testing framework.*
"""
        
        try:
            # Create GitHub issue comment
            subprocess.run([
                "gh", "issue", "comment", str(issue_number),
                "--body", comment_body
            ], check=True, cwd=self.project_root)
            
            print(f"✅ Updated GitHub issue #{issue_number} with test results")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to update GitHub issue #{issue_number}: {e}")
            return False
    
    def create_test_summary_issue(self, test_report):
        """Create a new GitHub issue with test summary."""
        summary = test_report["summary"]
        
        title = f"🧪 Offline Cloud Infrastructure Test Results - {datetime.now().strftime('%Y-%m-%d')}"
        
        body = f"""## Test Summary

**Overall Results:**
- ✅ Passed: {summary['passed']}/{summary['total_tests']} tests
- ❌ Failed: {summary['failed']}/{summary['total_tests']} tests
- 📊 Success Rate: {summary['success_rate']:.1f}%

## Detailed Results

"""
        
        for platform, result in test_report["test_results"].items():
            status = "✅ PASS" if result["success"] else "❌ FAIL"
            body += f"### {platform.upper()} Tests: {status}\n\n"
            
            if not result["success"] and result["stderr"]:
                body += f"**Error Details:**\n```\n{result['stderr'][:500]}...\n```\n\n"
        
        body += f"""
## Next Steps

1. **Review Failed Tests**: Check the error details above
2. **Fix Configuration Issues**: Update Terraform configurations as needed
3. **Re-run Tests**: Execute the offline testing suite again
4. **Deploy to Cloud**: Once all tests pass, proceed with cloud deployment

## Test Framework

The offline testing framework includes:
- AWS ECS/Fargate configuration validation
- GCP Compute Engine configuration validation
- Security best practices validation
- Terraform syntax and resource validation

**Test Command:**
```bash
./tests/tofu/offline-cloud-testing.sh
```

---
*Generated by the offline cloud infrastructure testing framework on {test_report['timestamp']}*
"""
        
        try:
            # Create GitHub issue
            result = subprocess.run([
                "gh", "issue", "create",
                "--title", title,
                "--body", body,
                "--label", "testing,infrastructure,automation"
            ], capture_output=True, text=True, check=True, cwd=self.project_root)
            
            issue_url = result.stdout.strip()
            print(f"✅ Created GitHub issue: {issue_url}")
            return issue_url
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to create GitHub issue: {e}")
            return None


def main():
    """Main function to run offline tests and update GitHub."""
    integration = GitHubIntegration()
    
    # Run offline tests
    test_results = integration.run_offline_tests()
    
    # Generate test report
    test_report = integration.generate_test_report()
    
    # Print summary
    summary = test_report["summary"]
    print(f"\n📊 Test Summary:")
    print(f"   Total Tests: {summary['total_tests']}")
    print(f"   Passed: {summary['passed']}")
    print(f"   Failed: {summary['failed']}")
    print(f"   Success Rate: {summary['success_rate']:.1f}%")
    
    # Update GitHub issues
    if os.getenv("GITHUB_TOKEN"):
        # Update existing issue if specified
        issue_number = os.getenv("GITHUB_ISSUE_NUMBER")
        if issue_number:
            integration.update_github_issue(issue_number, test_report)
        else:
            # Create new issue
            integration.create_test_summary_issue(test_report)
    else:
        print("⚠️  GITHUB_TOKEN not set, skipping GitHub integration")


if __name__ == "__main__":
    main()