/**
 * Base Vector Embedding Provider
 * Provides common functionality for all embedding providers
 */

import { IVectorEmbeddingProvider } from '../interfaces/vector-embedding-provider';

export abstract class BaseVectorEmbeddingProvider implements IVectorEmbeddingProvider {
  protected apiKey: string;
  protected model: string;
  protected dimension: number;
  protected options: Record<string, any>;

  constructor(
    apiKey: string,
    model: string,
    dimension: number,
    options: Record<string, any> = {}
  ) {
    this.apiKey = apiKey;
    this.model = model;
    this.dimension = dimension;
    this.options = options;
  }

  /**
   * Generate an embedding vector for the given text
   * This method should be implemented by subclasses
   */
  abstract generateEmbedding(text: string): Promise<number[]>;

  /**
   * Get the dimension of embeddings generated by this provider
   */
  getDimension(): number {
    return this.dimension;
  }

  /**
   * Get the model ID used by this provider
   */
  getModelId(): string {
    return this.model;
  }

  /**
   * Helper method to verify API key is set
   */
  protected verifyApiKey(): void {
    if (!this.apiKey) {
      throw new Error('API key is required for embedding provider');
    }
  }

  /**
   * Helper method to normalize text for embedding
   * Removes extra whitespace, trims, etc.
   */
  protected normalizeText(text: string): string {
    if (!text) return '';
    
    // Remove excessive whitespace
    return text
      .trim()
      .replace(/\s+/g, ' ')
      .substring(0, 8000); // Limit length for API compatibility
  }

  /**
   * Generate a zero vector as fallback
   */
  protected generateZeroVector(): number[] {
    return new Array(this.dimension).fill(0);
  }
}