/**
 * Type declarations for lucide-react
 * Provides basic type safety for Lucide React icon components
 */

declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    color?: string
    strokeWidth?: string | number
  }

  export type LucideIcon = ComponentType<LucideProps>

  // Common icons used in the application
  export const Send: LucideIcon
  export const Bot: LucideIcon
  export const User: LucideIcon
  export const Upload: LucideIcon
  export const Code: LucideIcon
  export const Settings: LucideIcon
  export const Sparkles: LucideIcon
  export const MessageSquare: LucideIcon
  export const Wand2: LucideIcon
  export const FileText: LucideIcon
  export const Play: LucideIcon
  export const Pause: LucideIcon
  export const Stop: LucideIcon
  export const Download: LucideIcon
  export const Copy: LucideIcon
  export const Check: LucideIcon
  export const X: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronUp: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const Plus: LucideIcon
  export const Minus: LucideIcon
  export const Edit: LucideIcon
  export const Trash: LucideIcon
  export const Save: LucideIcon
  export const Loader: LucideIcon
  export const AlertCircle: LucideIcon
  export const CheckCircle: LucideIcon
  export const XCircle: LucideIcon
  export const Info: LucideIcon
  export const Eye: LucideIcon
  export const EyeOff: LucideIcon
  export const Search: LucideIcon
  export const Filter: LucideIcon
  export const SortAsc: LucideIcon
  export const SortDesc: LucideIcon
  export const Menu: LucideIcon
  export const MoreVertical: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const Home: LucideIcon
  export const Folder: LucideIcon
  export const File: LucideIcon
  export const Terminal: LucideIcon
  export const Monitor: LucideIcon
  export const Smartphone: LucideIcon
  export const Tablet: LucideIcon
  export const Laptop: LucideIcon
  export const Desktop: LucideIcon
  export const Server: LucideIcon
  export const Database: LucideIcon
  export const Cloud: LucideIcon
  export const Wifi: LucideIcon
  export const WifiOff: LucideIcon
  export const Lock: LucideIcon
  export const Unlock: LucideIcon
  export const Key: LucideIcon
  export const Shield: LucideIcon
  export const ShieldCheck: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldX: LucideIcon
  export const Users: LucideIcon
  export const UserPlus: LucideIcon
  export const UserMinus: LucideIcon
  export const UserCheck: LucideIcon
  export const UserX: LucideIcon
  export const Star: LucideIcon
  export const Heart: LucideIcon
  export const Bookmark: LucideIcon
  export const Share: LucideIcon
  export const Link: LucideIcon
  export const ExternalLink: LucideIcon
  export const Mail: LucideIcon
  export const Phone: LucideIcon
  export const Calendar: LucideIcon
  export const Clock: LucideIcon
  export const Timer: LucideIcon
  export const Stopwatch: LucideIcon
  export const History: LucideIcon
  export const RotateCcw: LucideIcon
  export const RotateCw: LucideIcon
  export const RefreshCw: LucideIcon
  export const RefreshCcw: LucideIcon
  export const ArrowUp: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowUpDown: LucideIcon
  export const ArrowLeftRight: LucideIcon
  export const TrendingUp: LucideIcon
  export const TrendingDown: LucideIcon
  export const BarChart: LucideIcon
  export const LineChart: LucideIcon
  export const PieChart: LucideIcon
  export const Activity: LucideIcon
  export const Zap: LucideIcon
  export const Flash: LucideIcon
  export const Cpu: LucideIcon
  export const HardDrive: LucideIcon
  export const MemoryStick: LucideIcon
  export const Gauge: LucideIcon
  export const Volume: LucideIcon
  export const VolumeOff: LucideIcon
  export const Mic: LucideIcon
  export const MicOff: LucideIcon
  export const Camera: LucideIcon
  export const CameraOff: LucideIcon
  export const Video: LucideIcon
  export const VideoOff: LucideIcon
  export const Image: LucideIcon
  export const FileImage: LucideIcon
  export const FileVideo: LucideIcon
  export const FileAudio: LucideIcon
  export const FilePdf: LucideIcon
  export const FileSpreadsheet: LucideIcon
  export const FileDocument: LucideIcon
  export const Folder: LucideIcon
  export const FolderOpen: LucideIcon
  export const FolderPlus: LucideIcon
  export const Archive: LucideIcon
  export const Package: LucideIcon
  export const Box: LucideIcon
  export const Grid: LucideIcon
  export const List: LucideIcon
  export const Layers: LucideIcon
  export const Layout: LucideIcon
  export const Sidebar: LucideIcon
  export const PanelLeft: LucideIcon
  export const PanelRight: LucideIcon
  export const PanelTop: LucideIcon
  export const PanelBottom: LucideIcon
  export const Maximize: LucideIcon
  export const Minimize: LucideIcon
  export const Square: LucideIcon
  export const Circle: LucideIcon
  export const Triangle: LucideIcon
  export const Hexagon: LucideIcon
  export const Pentagon: LucideIcon
  export const Octagon: LucideIcon
  export const Diamond: LucideIcon
  export const Sparkle: LucideIcon
  export const Flame: LucideIcon
  export const Sun: LucideIcon
  export const Moon: LucideIcon
  export const CloudSun: LucideIcon
  export const CloudMoon: LucideIcon
  export const CloudRain: LucideIcon
  export const CloudSnow: LucideIcon
  export const CloudLightning: LucideIcon
  export const Thermometer: LucideIcon
  export const Droplets: LucideIcon
  export const Wind: LucideIcon
  export const Compass: LucideIcon
  export const Map: LucideIcon
  export const MapPin: LucideIcon
  export const Navigation: LucideIcon
  export const Route: LucideIcon
  export const Car: LucideIcon
  export const Bike: LucideIcon
  export const Bus: LucideIcon
  export const Train: LucideIcon
  export const Plane: LucideIcon
  export const Ship: LucideIcon
  export const Truck: LucideIcon
  export const Taxi: LucideIcon
  export const Fuel: LucideIcon
  export const Wrench: LucideIcon
  export const Hammer: LucideIcon
  export const Screwdriver: LucideIcon
  export const Scissors: LucideIcon
  export const Ruler: LucideIcon
  export const Paintbrush: LucideIcon
  export const Palette: LucideIcon
  export const Pipette: LucideIcon
  export const Brush: LucideIcon
  export const Pen: LucideIcon
  export const Pencil: LucideIcon
  export const Eraser: LucideIcon
  export const Highlighter: LucideIcon
  export const Type: LucideIcon
  export const Bold: LucideIcon
  export const Italic: LucideIcon
  export const Underline: LucideIcon
  export const Strikethrough: LucideIcon
  export const AlignLeft: LucideIcon
  export const AlignCenter: LucideIcon
  export const AlignRight: LucideIcon
  export const AlignJustify: LucideIcon
  export const Indent: LucideIcon
  export const Outdent: LucideIcon
  export const Quote: LucideIcon
  export const List: LucideIcon
  export const ListOrdered: LucideIcon
  export const Heading: LucideIcon
  export const Heading1: LucideIcon
  export const Heading2: LucideIcon
  export const Heading3: LucideIcon
  export const Heading4: LucideIcon
  export const Heading5: LucideIcon
  export const Heading6: LucideIcon
  export const Subscript: LucideIcon
  export const Superscript: LucideIcon
  export const Code2: LucideIcon
  export const Binary: LucideIcon
  export const Hash: LucideIcon
  export const AtSign: LucideIcon
  export const Percent: LucideIcon
  export const Dollar: LucideIcon
  export const Euro: LucideIcon
  export const Pound: LucideIcon
  export const Yen: LucideIcon
  export const Bitcoin: LucideIcon
  export const CreditCard: LucideIcon
  export const Wallet: LucideIcon
  export const Banknote: LucideIcon
  export const Coins: LucideIcon
  export const Receipt: LucideIcon
  export const ShoppingCart: LucideIcon
  export const ShoppingBag: LucideIcon
  export const Store: LucideIcon
  export const Storefront: LucideIcon
  export const Tag: LucideIcon
  export const Tags: LucideIcon
  export const Gift: LucideIcon
  export const GiftCard: LucideIcon
  export const Trophy: LucideIcon
  export const Award: LucideIcon
  export const Medal: LucideIcon
  export const Ribbon: LucideIcon
  export const Crown: LucideIcon
  export const Gem: LucideIcon
  export const Diamond: LucideIcon
  export const Coins: LucideIcon
  export const Target: LucideIcon
  export const Focus: LucideIcon
  export const Crosshair: LucideIcon
  export const Scope: LucideIcon
  export const Radar: LucideIcon
  export const Satellite: LucideIcon
  export const Radio: LucideIcon
  export const Antenna: LucideIcon
  export const Signal: LucideIcon
  export const Rss: LucideIcon
  export const Podcast: LucideIcon
  export const Headphones: LucideIcon
  export const Speaker: LucideIcon
  export const Megaphone: LucideIcon
  export const Voicemail: LucideIcon
  export const PhoneCall: LucideIcon
  export const PhoneIncoming: LucideIcon
  export const PhoneOutgoing: LucideIcon
  export const PhoneMissed: LucideIcon
  export const PhoneForwarded: LucideIcon
  export const MessageCircle: LucideIcon
  export const Messages: LucideIcon
  export const MessageSquarePlus: LucideIcon
  export const MessageSquareMinus: LucideIcon
  export const MessageSquareText: LucideIcon
  export const MessageSquareEdit: LucideIcon
  export const MessageSquareReply: LucideIcon
  export const MessageSquareShare: LucideIcon
  export const MessageSquareHeart: LucideIcon
  export const MessageSquareDot: LucideIcon
  export const MessageSquareWarning: LucideIcon
  export const MessageSquareX: LucideIcon
  export const MessageSquareOff: LucideIcon
  export const MessageSquareCode: LucideIcon
  export const MessageSquareQuote: LucideIcon
  export const MessageSquareDashed: LucideIcon
  export const MessageSquareMore: LucideIcon
  export const Smile: LucideIcon
  export const Frown: LucideIcon
  export const Meh: LucideIcon
  export const Laugh: LucideIcon
  export const Angry: LucideIcon
  export const Surprised: LucideIcon
  export const Worried: LucideIcon
  export const Sleeping: LucideIcon
  export const Dizzy: LucideIcon
  export const Cool: LucideIcon
  export const Wink: LucideIcon
  export const Kiss: LucideIcon
  export const HeartEyes: LucideIcon
  export const Sunglasses: LucideIcon
  export const Party: LucideIcon
  export const Mask: LucideIcon
  export const Robot: LucideIcon
  export const Alien: LucideIcon
  export const Ghost: LucideIcon
  export const Skull: LucideIcon
  export const Zombie: LucideIcon
  export const Monster: LucideIcon
  export const Vampire: LucideIcon
  export const Witch: LucideIcon
  export const Wizard: LucideIcon
  export const Mage: LucideIcon
  export const Ninja: LucideIcon
  export const Pirate: LucideIcon
  export const Knight: LucideIcon
  export const Princess: LucideIcon
  export const Prince: LucideIcon
  export const King: LucideIcon
  export const Queen: LucideIcon
  export const Baby: LucideIcon
  export const Child: LucideIcon
  export const Adult: LucideIcon
  export const Elder: LucideIcon
  export const Person: LucideIcon
  export const PersonStanding: LucideIcon
  export const PersonWalking: LucideIcon
  export const PersonRunning: LucideIcon
  export const PersonSitting: LucideIcon
  export const PersonLying: LucideIcon
  export const PersonRaiseHand: LucideIcon
  export const PersonArmsSpread: LucideIcon
  export const PersonInBed: LucideIcon
  export const PersonSwimming: LucideIcon
  export const PersonBiking: LucideIcon
  export const PersonSkiing: LucideIcon
  export const PersonSurfing: LucideIcon
  export const PersonClimbing: LucideIcon
  export const PersonGolfing: LucideIcon
  export const PersonPlaying: LucideIcon
  export const PersonDancing: LucideIcon
  export const PersonJuggling: LucideIcon
  export const PersonMeditating: LucideIcon
  export const PersonYoga: LucideIcon
  export const PersonMassage: LucideIcon
  export const PersonHaircut: LucideIcon
  export const PersonInSauna: LucideIcon
  export const PersonInLotusPosition: LucideIcon
  export const PersonKneeling: LucideIcon
  export const PersonFacepalm: LucideIcon
  export const PersonShrugging: LucideIcon
  export const PersonBowing: LucideIcon
  export const PersonTippingHand: LucideIcon
  export const PersonGesturingNo: LucideIcon
  export const PersonGesturingOk: LucideIcon
  export const PersonPointing: LucideIcon
  export const PersonPointingUp: LucideIcon
  export const PersonPointingDown: LucideIcon
  export const PersonPointingLeft: LucideIcon
  export const PersonPointingRight: LucideIcon

  // Default export (if any)
  const lucideReact: {
    [key: string]: LucideIcon
  }
  export default lucideReact
}