{{- if .Values.workspace.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-server-cloud.fullname" . }}-workspace
  labels:
    {{- include "code-server-cloud.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.workspace.persistentVolume.size }}
  {{- if .Values.workspace.persistentVolume.storageClass }}
  storageClassName: {{ .Values.workspace.persistentVolume.storageClass }}
  {{- end }}
{{- end }}
