#!/bin/sh
#
# PROVIDE: td_event_emitter
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add to rc.conf: td_event_emitter_enable="YES"
#
. /etc/rc.subr

name="td_event_emitter"
rcvar=td_event_emitter_enable

command="/usr/local/bin/node"
command_args="/usr/local/gt/daemon/kafka-dsm/td-event-emitter.js"

load_rc_config $name
: ${td_event_emitter_enable:=no}

run_rc_command "$1"
