/**
 * Vector Embedding Provider Interface
 * Defines the contract that all embedding providers must implement
 */

export interface IVectorEmbeddingProvider {
  /**
   * Generate an embedding vector for the given text
   * @param text The text to generate an embedding for
   * @returns Promise resolving to a numeric array representing the embedding
   */
  generateEmbedding(text: string): Promise<number[]>;
  
  /**
   * Get the dimension of embeddings generated by this provider
   * @returns The dimension (length) of the embedding vectors
   */
  getDimension(): number;
  
  /**
   * Get the model ID used by this provider
   * @returns The model ID as a string
   */
  getModelId(): string;
}