{{- if .Values.chatUi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-chat-ui-secrets
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: chat-ui
type: Opaque
data:
  # MongoDB connection string
  mongodb-url: {{ printf "mongodb://%s:%s@%s:%d/%s" 
    .Values.mongodb.auth.username 
    .Values.mongodb.auth.password 
    (include "vibecode-platform.mongodb.fullname" .) 
    (.Values.mongodb.service.ports.mongodb | int) 
    .Values.mongodb.auth.database | b64enc }}
  
  # Hugging Face access token (optional)
  {{- if .Values.chatUi.secrets.hfAccessToken }}
  hf-access-token: {{ .Values.chatUi.secrets.hfAccessToken | b64enc }}
  {{- end }}
  
  # Rate limiting secret
  rate-limit-secret: {{ .Values.chatUi.secrets.rateLimitSecret | default (randAlphaNum 32) | b64enc }}
  
  # Parquet export secret (optional)
  {{- if .Values.chatUi.secrets.parquetExportSecret }}
  parquet-export-secret: {{ .Values.chatUi.secrets.parquetExportSecret | b64enc }}
  {{- end }}
  
  # Web search API keys (optional)
  {{- if .Values.chatUi.secrets.webSearch }}
  {{- if .Values.chatUi.secrets.webSearch.serpApiKey }}
  serp-api-key: {{ .Values.chatUi.secrets.webSearch.serpApiKey | b64enc }}
  {{- end }}
  {{- if .Values.chatUi.secrets.webSearch.bingApiKey }}
  bing-api-key: {{ .Values.chatUi.secrets.webSearch.bingApiKey | b64enc }}
  {{- end }}
  {{- end }}
  
  # Additional secrets
  {{- with .Values.chatUi.secrets.extra }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}