{{- if .Values.redis.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "vibecode-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-redis-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vibecode-platform.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vibecode-platform.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
      annotations:
        {{- if .Values.datadog.enabled }}
        ad.datadoghq.com/redis.check_names: '["redisdb"]'
        ad.datadoghq.com/redis.init_configs: '[{}]'
        ad.datadoghq.com/redis.instances: |
          [
            {
              "host": "%%host%%",
              "port": 6379,
              "tags": ["env:{{ .Values.global.nodeEnv | default "production" }}", "service:redis", "version:{{ .Values.redis.image.tag }}"]
            }
          ]
        ad.datadoghq.com/tags: '{"env": "{{ .Values.global.nodeEnv | default "production" }}", "service": "redis", "version": "{{ .Values.redis.image.tag }}"}'
        {{- end }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: IfNotPresent
        command:
          - redis-server
          - --save 900 1
          - --save 300 10
          - --save 60 10000
          - --loglevel notice
          - --maxmemory {{ .Values.redis.commandArgs.maxmemory }}
          - --maxmemory-policy allkeys-lru
          - --appendonly yes
          - --appendfsync everysec
        ports:
        - containerPort: 6379
          name: redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        env:
        {{- if .Values.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_SERVICE
          value: "redis"
        - name: DD_ENV
          value: {{ .Values.global.nodeEnv | default "production" | quote }}
        - name: DD_VERSION
          value: {{ .Values.redis.image.tag | quote }}
        {{- end }}
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ include "vibecode-platform.fullname" . }}-redis-pvc
{{- end }}
