{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-web
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "vibecode-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "vibecode-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.web.nodeEnv | quote }}
            {{- if .Values.web.datadog.rum.enabled }}
            - name: NEXT_PUBLIC_DATADOG_APPLICATION_ID
              value: {{ .Values.web.datadog.rum.applicationId | quote }}
            - name: NEXT_PUBLIC_DATADOG_CLIENT_TOKEN
              value: {{ .Values.web.datadog.rum.clientToken | quote }}
            - name: NEXT_PUBLIC_DATADOG_SITE
              value: {{ .Values.web.datadog.rum.site | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
