{{- if .Values.websocket.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibecode-platform.fullname" . }}-websocket
  labels:
    {{- include "vibecode-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vibecode-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
{{- end }}
