#!/usr/bin/env python3

# Datadog Unified Service Tagging
_dd_service = "apply-triage-labels"
_dd_env = __import__("os").environ.get("DD_ENV", "development")
_dd_version = __import__("os").environ.get("DD_VERSION", "0.1.0")
try:
    from ddtrace import config as _dd_config, patch_all as _dd_patch, tracer as _dd_tracer
    _dd_config.service = _dd_service
    _dd_config.env = _dd_env
    _dd_config.version = _dd_version
    _dd_tracer.set_tags({"team": "platform", "component": "scripts"})
    _dd_patch()
except ImportError:
    pass


# Datadog Log Aggregation
from scripts.lib.log_aggregation import get_log_aggregation


# -- VibeCode Telemetry --
import sys
import os

# Initialize log aggregation
log_agg = get_log_aggregation()

try:
    sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), './')))
    from vibecode.telemetry import init_telemetry
    tracer = init_telemetry(os.path.basename(__file__))
except ImportError:
    pass
# ------------------------

"""
Apply triage labels to GitHub issues using recommendations.
Generates a shell script to execute gh commands.
"""
try:
    import os as _os; _c = __import__('ddtrace').config; _s = _os.path.basename(__file__).replace('.py',''); _c.service = _s; _c.requests.service = _s; __import__('ddtrace').patch_all()
except: pass


import json
import sys


def generate_label_commands(recommendations_file: str, output_script: str) -> None:
    """Generate shell script with gh commands to apply labels."""
    
    # Load recommendations
    with open(recommendations_file, 'r') as f:
        data = json.load(f)
    
    recommendations = data['recommendations']
    
    # Filter to only issues that need labels
    issues_to_update = [r for r in recommendations if r['new_labels'] and r['needs_triage']]
    
    print(f"Found {len(issues_to_update)} issues that need label updates")
    
    # Generate shell script
    commands = []
    commands.append("#!/bin/bash")
    commands.append("# Auto-generated script to apply triage labels")
    commands.append("# Generated by apply_triage_labels.py")
    commands.append("")
    commands.append("set -e  # Exit on error")
    commands.append("")
    commands.append('REPO="ryanmaclean/vibecode-webgui"')
    commands.append("COUNT=0")
    commands.append("TOTAL=%d" % len(issues_to_update))
    commands.append("")
    commands.append("echo 'Starting to apply labels to $TOTAL issues...'")
    commands.append("echo")
    commands.append("")
    
    for issue in issues_to_update:
        issue_number = issue['number']
        new_labels = issue['new_labels']
        title = issue['title'][:60]
        
        if not new_labels:
            continue
        
        # Build gh command
        label_args = []
        for label in new_labels:
            label_args.append(f'--add-label "{label}"')
        
        commands.append(f"# Issue #{issue_number}: {title}")
        commands.append("echo \"Processing #%d: %s...\"" % (issue_number, title.replace('"', '\\"')))
        commands.append(
            f"gh issue edit {issue_number} --repo $REPO {' '.join(label_args)} && ((COUNT++))"
        )
        commands.append("sleep 0.5  # Rate limiting")
        commands.append("")
    
    commands.append("echo")
    commands.append('echo "Applied labels to $COUNT/$TOTAL issues"')
    commands.append("echo 'Triage complete!'")
    
    # Write script
    with open(output_script, 'w') as f:
        f.write('\n'.join(commands))
    
    print(f"Generated shell script: {output_script}")
    print(f"To apply labels, run: bash {output_script}")


def main():
    """Main function."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate script to apply triage labels')
    parser.add_argument('recommendations_file',
                       help='JSON file with triage recommendations')
    parser.add_argument('--output', '-o',
                       default='/tmp/apply_triage.sh',
                       help='Output shell script path')
    args = parser.parse_args()
    
    generate_label_commands(args.recommendations_file, args.output)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())