-- Vector Embeddings Schema for Azure OpenAI Integration
-- This schema is optimized for pgvector with Azure OpenAI embeddings

-- Enable pgvector extension if not already enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Create embeddings table for storing document embeddings
CREATE TABLE IF NOT EXISTS embeddings (
  id SERIAL PRIMARY KEY,
  document_id VARCHAR(255) NOT NULL UNIQUE,
  content TEXT NOT NULL,
  embedding VECTOR(1536),  -- Azure OpenAI embeddings are 1536 dimensions by default
  metadata JSONB DEFAULT '{}'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on document_id for fast lookups
CREATE INDEX IF NOT EXISTS idx_embeddings_document_id ON embeddings (document_id);

-- Create GIN index on metadata for efficient filtering
CREATE INDEX IF NOT EXISTS idx_embeddings_metadata ON embeddings USING GIN (metadata);

-- Create a function to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at on row update
DROP TRIGGER IF EXISTS update_embeddings_updated_at ON embeddings;
CREATE TRIGGER update_embeddings_updated_at
BEFORE UPDATE ON embeddings
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Create ivfflat index for faster similarity search
-- Note: This should be created after data is loaded for better performance
-- CREATE INDEX IF NOT EXISTS idx_embeddings_vector ON embeddings USING ivfflat (embedding vector_l2_ops) WITH (lists = 100);

-- Create a view for embedding statistics
CREATE OR REPLACE VIEW embedding_stats AS
SELECT 
  date_trunc('hour', created_at) AS hour_bucket,
  COUNT(*) AS total_embeddings,
  AVG(LENGTH(content)) AS avg_content_length,
  COUNT(DISTINCT document_id) AS unique_documents,
  'azure' AS provider
FROM 
  embeddings
GROUP BY 
  hour_bucket
ORDER BY 
  hour_bucket DESC;

-- Create a function to cleanup old embeddings (optional)
CREATE OR REPLACE FUNCTION cleanup_old_embeddings(age_in_days INTEGER DEFAULT 30)
RETURNS INTEGER AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM embeddings
  WHERE updated_at < NOW() - (age_in_days * INTERVAL '1 day')
  RETURNING COUNT(*) INTO deleted_count;
  
  RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

-- Add a comment to the embeddings table
COMMENT ON TABLE embeddings IS 'Stores document embeddings generated by Azure OpenAI';

-- Grants (adjust according to your user/role setup)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON embeddings TO vibecode_app;
-- GRANT USAGE, SELECT ON SEQUENCE embeddings_id_seq TO vibecode_app;