#!/usr/bin/env bash
set -euo pipefail

CLUSTER=${CLUSTER:-vibecode}
KIND_CONFIG=${KIND_CONFIG:-k8s/kind-test-config.yaml}
APP_IMAGE=${APP_IMAGE:-vibecode-webgui:latest}
DOCKERFILE=${DOCKERFILE:-docker/Dockerfile}
DOCKERFILE_TARGET=${DOCKERFILE_TARGET:-development}
NAMESPACE=${NAMESPACE:-vibecode-platform}
DELETE_EXISTING=${DELETE_EXISTING:-true}
INGRESS_ENABLED=${INGRESS_ENABLED:-true}

log() {
  printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*"
}

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "Missing dependency: $1"
    exit 1
  fi
}

log "validating local tooling"
require docker
require kind
require kubectl
require openssl
require helm

ENV_FILE=${ENV_FILE:-.env.local}
if [ -f "$ENV_FILE" ]; then
  log "loading environment overrides from $ENV_FILE"
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

if ! docker info >/dev/null 2>&1; then
  log "unable to communicate with Docker daemon; ensure Docker Desktop/colima is running and accessible"
  exit 1
fi

if [ ! -f "$DOCKERFILE" ]; then
  log "Dockerfile '$DOCKERFILE' not found"
  exit 1
fi

NEXTAUTH_SECRET_VALUE=${NEXTAUTH_SECRET_VALUE:-${NEXTAUTH_SECRET:-$(openssl rand -base64 32)}}

if [ "${SKIP_BUILD:-0}" = "1" ]; then
  log "SKIP_BUILD=1 set; skipping application image build"
else
  log "building application image using $DOCKERFILE"
  docker build -f "$DOCKERFILE" --target "$DOCKERFILE_TARGET" -t "$APP_IMAGE" .
fi

if kind get clusters | grep -q "^${CLUSTER}$"; then
  if [ "$DELETE_EXISTING" = "true" ]; then
    log "deleting existing KIND cluster '$CLUSTER'"
    kind delete cluster --name "$CLUSTER"
  else
    log "re-using existing KIND cluster '$CLUSTER'"
  fi
fi

create_cluster() {
  local config_file="$1"
  local log_file="$2"
  set +e
  kind create cluster --name "$CLUSTER" --config "$config_file" 2>&1 | tee "$log_file"
  local rc=${PIPESTATUS[0]}
  set -e
  return $rc
}

fallback_config() {
  tmp_cfg=$(mktemp)
  cat > "$tmp_cfg" <<'EOF'
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
- role: worker
EOF
  echo "$tmp_cfg"
}

ensure_datadog() {
  local dd_namespace=${DD_NAMESPACE:-datadog}

  if [ -z "${DD_API_KEY:-}" ]; then
    log "DD_API_KEY is required to install Datadog. Set it in $ENV_FILE or the environment."
    exit 1
  fi

  log "creating Datadog namespace '${dd_namespace}'"
  kubectl create namespace "$dd_namespace" --dry-run=client -o yaml | kubectl apply -f -

  log "creating Datadog secret"
  local secret_args=(--from-literal=api-key="${DD_API_KEY}")
  if [ -n "${DD_APP_KEY:-}" ]; then
    secret_args+=(--from-literal=app-key="${DD_APP_KEY}")
  fi
  kubectl -n "$dd_namespace" create secret generic datadog-secret "${secret_args[@]}" \
    --dry-run=client -o yaml | kubectl apply -f -

  log "creating Datadog cluster agent auth secret"
  local cluster_agent_token_value=${DD_CLUSTER_AGENT_TOKEN:-$(openssl rand -hex 32)}
  kubectl -n "$dd_namespace" create secret generic datadog-cluster-agent-token \
    --from-literal=token="$cluster_agent_token_value" \
    --dry-run=client -o yaml | kubectl apply -f -

  log "creating Datadog configuration map"
  kubectl -n "$dd_namespace" create configmap datadog-config \
    --from-literal=datadog.yaml="## Autogenerated by min-kind-bootstrap" \
    --dry-run=client -o yaml | kubectl apply -f -

  local ca_bundle
  ca_bundle=$(kubectl get configmap kube-root-ca.crt -n kube-public -o jsonpath='{.data.ca\.crt}' 2>/dev/null || echo "")
  if [ -n "$ca_bundle" ]; then
    kubectl -n "$dd_namespace" create configmap kube-root-ca.crt \
      --from-literal=ca.crt="$ca_bundle" \
      --dry-run=client -o yaml | kubectl apply -f -
  else
    log "warning: unable to source kube-root-ca bundle for datadog namespace"
  fi

  log "installing Datadog via Helm"
  helm repo add datadog https://helm.datadoghq.com >/dev/null 2>&1 || true
  helm repo update datadog >/dev/null 2>&1 || true
  helm upgrade --install datadog datadog/datadog \
    --namespace "$dd_namespace" \
    --create-namespace \
    --wait \
    --timeout 15m \
    -f k8s/datadog-values-kind.yaml

  log "waiting for Datadog agent pods"
  kubectl -n "$dd_namespace" wait --for=condition=Ready pod -l app=datadog-agent --timeout=600s
  log "waiting for Datadog Cluster Agent pods"
  kubectl -n "$dd_namespace" wait --for=condition=Ready pod -l app=datadog-cluster-agent --timeout=600s
}

fallback_used=false

if ! kind get clusters | grep -q "^${CLUSTER}$"; then
  attempt_config="$KIND_CONFIG"
  while true; do
    log "creating KIND cluster '$CLUSTER' via $attempt_config"
    tmp_log=$(mktemp)
    if create_cluster "$attempt_config" "$tmp_log"; then
      rm -f "$tmp_log"
      break
    fi

    if [ "$fallback_used" = false ]; then
      log "kind cluster creation failed (see log below); attempting fallback config"
      tail -n 20 "$tmp_log" || cat "$tmp_log"
      fallback_used=true
      attempt_config=$(fallback_config)
      kind delete cluster --name "$CLUSTER" >/dev/null 2>&1 || true
      rm -f "$tmp_log"
      continue
    fi

    log "kind cluster creation failed even after fallback"
    cat "$tmp_log"
    rm -f "$tmp_log"
    exit 1
  done
else
  log "cluster '$CLUSTER' already running"
fi

if [ "$fallback_used" = true ]; then
  log "cluster created using fallback config without host port mappings"
  rm -f "$attempt_config"
fi

log "installing Datadog agent"
ensure_datadog

log "loading image $APP_IMAGE into KIND"
kind load docker-image "$APP_IMAGE" --name "$CLUSTER"

log "ensuring namespace $NAMESPACE exists"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

log "applying storage class"
kubectl apply -f storage-class.yaml

log "applying database bootstrap configmap"
kubectl apply -f k8s/postgres-init-configmap.yaml

log "deploying postgres"
kubectl apply -f k8s/postgres-deployment.yaml

log "deploying valkey"
kubectl apply -f k8s/valkey-deployment.yaml

log "waiting for postgres readiness"
kubectl -n "$NAMESPACE" rollout status deployment/postgres --timeout=300s

log "waiting for valkey readiness"
kubectl -n "$NAMESPACE" rollout status deployment/valkey --timeout=300s

log "creating vibecode secrets"
kubectl -n "$NAMESPACE" create secret generic vibecode-secrets \
  --from-literal=ADMIN_EMAIL="${ADMIN_EMAIL:-admin@vibecode.dev}" \
  --from-literal=ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin123}" \
  --from-literal=NODE_ENV="${NODE_ENV:-production}" \
  --from-literal=DD_API_KEY="${DD_API_KEY:-placeholder-dd-api-key}" \
  --from-literal=DD_APP_KEY="${DD_APP_KEY:-placeholder-dd-app-key}" \
  --from-literal=NEXT_PUBLIC_DD_APPLICATION_ID="${NEXT_PUBLIC_DD_APPLICATION_ID:-placeholder-app-id}" \
  --from-literal=NEXT_PUBLIC_DD_CLIENT_TOKEN="${NEXT_PUBLIC_DD_CLIENT_TOKEN:-placeholder-client-token}" \
  --from-literal=NEXT_PUBLIC_DD_SITE="${NEXT_PUBLIC_DD_SITE:-datadoghq.com}" \
  --from-literal=OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-placeholder-openrouter-key}" \
  --from-literal=NEXTAUTH_SECRET="${NEXTAUTH_SECRET_VALUE}" \
  --dry-run=client -o yaml | kubectl apply -f -

log "creating oauth placeholder secret"
kubectl -n "$NAMESPACE" create secret generic oauth-secrets \
  --from-literal=GITHUB_ID="${GITHUB_ID:-dummy}" \
  --from-literal=GITHUB_SECRET="${GITHUB_SECRET:-dummy}" \
  --from-literal=GOOGLE_ID="${GOOGLE_ID:-dummy}" \
  --from-literal=GOOGLE_SECRET="${GOOGLE_SECRET:-dummy}" \
  --from-literal=NEXTAUTH_SECRET="${OAUTH_NEXTAUTH_SECRET:-dummy}" \
  --from-literal=NEXTAUTH_URL="${NEXTAUTH_URL:-http://localhost:3000}" \
  --dry-run=client -o yaml | kubectl apply -f -

log "applying vibecode deployment manifest"
kubectl apply -f k8s/vibecode-deployment.yaml

log "scaling vibecode deployment to zero while migrations run"
kubectl -n "$NAMESPACE" scale deployment/vibecode-webgui --replicas=0

log "ensuring previous migration job removed"
kubectl -n "$NAMESPACE" delete job vibecode-migrations --ignore-not-found

log "running prisma migrations job"
kubectl apply -f k8s/vibecode-migrations-job.yaml
set +e
kubectl -n "$NAMESPACE" wait --for=condition=complete job/vibecode-migrations --timeout=300s
wait_rc=$?
set -e
if [ $wait_rc -ne 0 ]; then
  log "prisma migrations job did not complete within timeout; inspecting status"

  get_job_field() {
    local field="$1"
    local value
    value=$(kubectl -n "$NAMESPACE" get job vibecode-migrations -o jsonpath="{$field}" 2>/dev/null || echo "")
    if [ -z "$value" ]; then
      echo 0
    else
      echo "$value"
    fi
  }

  job_failed=$(get_job_field '.status.failed')
  job_succeeded=$(get_job_field '.status.succeeded')
  job_active=$(get_job_field '.status.active')

  job_logs=""
  for attempt in 1 2 3 4 5 6 7 8 9 10; do
    job_logs=$(kubectl -n "$NAMESPACE" logs job/vibecode-migrations 2>/dev/null || true)
    if [ -n "$job_logs" ]; then
      break
    fi
    pod_name=$(kubectl -n "$NAMESPACE" get pods -l job-name=vibecode-migrations -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
    if [ -n "$pod_name" ]; then
      job_logs=$(kubectl -n "$NAMESPACE" logs "$pod_name" 2>/dev/null || true)
      if [ -n "$job_logs" ]; then
        break
      fi
    fi
    sleep 2
  done

  if [ "$job_succeeded" -gt 0 ]; then
    log "prisma migrations job reported completion despite timeout"
  elif echo "$job_logs" | grep -q "P3005"; then
    log "prisma migrations detected existing schema; skipping baseline (P3005)"
    kubectl -n "$NAMESPACE" delete job vibecode-migrations --ignore-not-found >/dev/null 2>&1 || true
  elif [ "$job_failed" -gt 0 ]; then
    log "prisma migrations job failed"
    printf '%s\n' "$job_logs"
    exit 1
  elif [ "$job_active" -gt 0 ]; then
    log "prisma migrations job still active after timeout; deleting job to continue"
    printf '%s\n' "$job_logs"
    kubectl -n "$NAMESPACE" delete job vibecode-migrations --ignore-not-found >/dev/null 2>&1 || true
  else
    log "prisma migrations job status indeterminate"
    printf '%s\n' "$job_logs"
    exit 1
  fi
fi

log "scaling vibecode deployment back to desired replicas"
kubectl -n "$NAMESPACE" scale deployment/vibecode-webgui --replicas=2
kubectl -n "$NAMESPACE" rollout status deployment/vibecode-webgui --timeout=300s

if [ "$INGRESS_ENABLED" = "true" ]; then
  if kubectl get namespace ingress-nginx >/dev/null 2>&1; then
    log "applying minimal ingress"
    kubectl apply -f k8s/vibecode-ingress-min.yaml
  else
    log "skipping ingress apply (ingress-nginx namespace not found)"
  fi
fi

log "cluster bootstrap complete"
log "vibecode service available via NodePort 30000 or kubectl port-forward"
log "if ingress deployed, add '127.0.0.1 vibecode.local' to /etc/hosts"
