#!/bin/bash
# OpenVSCode entrypoint that configures database password from shared secret

PASSWORD_FILE=/run/secrets/db_password
SETTINGS_DIR=/home/.openvscode-server/data/User

# Wait for password file to exist (generated by init-secrets container)
echo "Waiting for database password to be generated..."
for i in {1..30}; do
    if [ -f "$PASSWORD_FILE" ]; then
        echo "Password file found!"
        break
    fi
    echo "Waiting... ($i/30)"
    sleep 1
done

if [ ! -f "$PASSWORD_FILE" ]; then
    echo "ERROR: Password file not found after 30 seconds"
    exit 1
fi

# Read the password
DB_PASSWORD=$(cat "$PASSWORD_FILE")

# Create settings directory (user should have permissions here)
mkdir -p "$SETTINGS_DIR"

# Create settings.json with the generated password
cat > "$SETTINGS_DIR/settings.json" << EOF_INNER
{
  "workspaceRag.pgHost": "postgres-pgvector",
  "workspaceRag.pgPort": 5432,
  "workspaceRag.pgDatabase": "workspace_rag",
  "workspaceRag.pgUser": "postgres",
  "workspaceRag.pgPassword": "$DB_PASSWORD",
  "workspaceRag.useMLX": false
}
EOF_INNER

echo "OpenVSCode settings configured with generated password"
echo "Settings written to: $SETTINGS_DIR/settings.json"

# Start OpenVSCode Server
exec /home/.openvscode-server/bin/openvscode-server \
    --host 0.0.0.0 \
    --port 3000 \
    --without-connection-token \
    "$@"
