#!/usr/bin/env npx tsx

/**
 * Seed demo rows for the document_embeddings and rag_chunks tables
 * to unblock local pgvector + Datadog DBM verification without cloud infra.
 */

import { PrismaClient } from '@prisma/client'
import { randomUUID } from 'crypto'

const prisma = new PrismaClient()

const VECTOR_DIMENSION = 1536

function generateVectorLiteral(size: number = VECTOR_DIMENSION): string {
  const values = Array.from({ length: size }, () => (Math.random() * 2 - 1))
  return `[${values.map((value) => value.toFixed(6)).join(',')}]`
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

function estimateTokens(content: string): number {
  return Math.max(1, Math.round(content.length / 4))
}

async function ensureVectorSchema() {
  await prisma.$executeRawUnsafe('CREATE EXTENSION IF NOT EXISTS vector')
  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS document_embeddings (
      id SERIAL PRIMARY KEY,
      document_id TEXT NOT NULL,
      content TEXT NOT NULL,
      embedding vector(${VECTOR_DIMENSION}),
      metadata JSONB DEFAULT '{}',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `)
  await prisma.$executeRawUnsafe('ALTER TABLE document_embeddings ADD COLUMN IF NOT EXISTS title TEXT')
  await prisma.$executeRawUnsafe('ALTER TABLE document_embeddings ADD COLUMN IF NOT EXISTS category TEXT')
  await prisma.$executeRawUnsafe('ALTER TABLE document_embeddings ADD COLUMN IF NOT EXISTS embedding_generation_time_ms INTEGER')
  await prisma.$executeRawUnsafe('ALTER TABLE document_embeddings ADD COLUMN IF NOT EXISTS search_count INTEGER DEFAULT 0')
  await prisma.$executeRawUnsafe('ALTER TABLE document_embeddings ADD COLUMN IF NOT EXISTS last_accessed_at TIMESTAMPTZ')
  await prisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS document_embeddings_document_id_idx ON document_embeddings(document_id)')
  await prisma.$executeRawUnsafe('CREATE UNIQUE INDEX IF NOT EXISTS document_embeddings_document_id_unique ON document_embeddings(document_id)')
  await prisma.$executeRawUnsafe('CREATE INDEX IF NOT EXISTS document_embeddings_category_idx ON document_embeddings(category)')
  await prisma.$executeRawUnsafe(`
    CREATE INDEX IF NOT EXISTS document_embeddings_embedding_l2_idx
      ON document_embeddings
      USING ivfflat (embedding vector_l2_ops)
      WITH (lists = 100)
  `)
}

async function seedRelationalScaffold() {
  const user = await prisma.user.upsert({
    where: { email: 'demo@vibecode.dev' },
    update: { name: 'Vector Demo User', role: 'admin' },
    create: {
      email: 'demo@vibecode.dev',
      name: 'Vector Demo User',
      role: 'admin'
    }
  })

  const workspace = await prisma.workspace.upsert({
    where: { workspace_id: 'vector-demo-workspace' },
    update: { name: 'Vector Demo Workspace' },
    create: {
      name: 'Vector Demo Workspace',
      description: 'Workspace generated by seed-document-embeddings.ts',
      user_id: user.id,
      status: 'active',
      workspace_id: 'vector-demo-workspace',
      url: 'https://example.local/vector-demo'
    }
  })

  let project = await prisma.project.findFirst({
    where: { workspace_id: workspace.id, name: 'Vector Demo Project' }
  })

  if (project) {
    project = await prisma.project.update({
      where: { id: project.id },
      data: {
        description: 'Seeded project containing sample docs for RAG verification',
        language: 'typescript',
        framework: 'nextjs',
        status: 'active'
      }
    })
  } else {
    project = await prisma.project.create({
      data: {
        name: 'Vector Demo Project',
        description: 'Seeded project containing sample docs for RAG verification',
        user_id: workspace.user_id,
        workspace_id: workspace.id,
        language: 'typescript',
        framework: 'nextjs',
        status: 'active'
      }
    })
  }

  let file = await prisma.file.findFirst({
    where: { path: 'docs/vector-demo.md', workspace_id: workspace.id }
  })

  const fileData = {
    name: 'vector-demo.md',
    path: 'docs/vector-demo.md',
    content: '# Vector Demo\n\nThis file was generated by the seed script to enable local testing.',
    size: 512,
    mime_type: 'text/markdown',
    language: 'markdown',
    lines: 12,
    user_id: user.id,
    workspace_id: workspace.id,
    project_id: project.id
  }

  if (file) {
    file = await prisma.file.update({ where: { id: file.id }, data: fileData })
  } else {
    file = await prisma.file.create({ data: fileData })
  }

  return { user, workspace, project, file }
}

async function seedDocumentEmbeddings() {
  const documents = [
    {
      documentId: 'ops/aks-platform-hardening',
      title: 'AKS Platform Hardening Checklist',
      category: 'kubernetes',
      content: 'Checklist covering node pool security, network policies, and admission controls for AKS.',
      metadata: { source: 'seed-script', topic: 'aks', version: '1.0.0' }
    },
    {
      documentId: 'observability/datadog-apm-tuning',
      title: 'Datadog APM Tuning Guide',
      category: 'observability',
      content: 'Step-by-step guidance for enabling traces, logs correlation, and runtime metrics in VibeCode services.',
      metadata: { source: 'seed-script', topic: 'datadog', version: '1.0.0' }
    },
    {
      documentId: 'rag/pipeline-resiliency',
      title: 'RAG Pipeline Resiliency Patterns',
      category: 'ai-platform',
      content: 'Strategies for ensuring robust retrieval augmented generation workflows across embedding providers.',
      metadata: { source: 'seed-script', topic: 'rag', version: '1.0.0' }
    }
  ]

  for (const doc of documents) {
    const embeddingLiteral = generateVectorLiteral()
    const metadataJson = JSON.stringify(doc.metadata)
    const duration = Math.floor(Math.random() * 200) + 50

    const insertSql = `
      INSERT INTO document_embeddings (
        document_id, title, content, category, embedding, metadata,
        embedding_generation_time_ms, search_count, updated_at
      ) VALUES (
        ${sqlString(doc.documentId)},
        ${sqlString(doc.title)},
        ${sqlString(doc.content)},
        ${sqlString(doc.category)},
        '${embeddingLiteral}'::vector,
        ${sqlString(metadataJson)}::jsonb,
        ${duration},
        0,
        NOW()
      )
      ON CONFLICT (document_id) DO UPDATE SET
        title = EXCLUDED.title,
        content = EXCLUDED.content,
        category = EXCLUDED.category,
        embedding = EXCLUDED.embedding,
        metadata = EXCLUDED.metadata,
        embedding_generation_time_ms = EXCLUDED.embedding_generation_time_ms,
        updated_at = NOW();
    `

    await prisma.$executeRawUnsafe(insertSql)
  }

  const [{ count }] = await prisma.$queryRaw<Array<{ count: number }>>`
    SELECT COUNT(*)::int AS count FROM document_embeddings
  `

  return count
}

async function seedRagChunks(fileId: number, workspaceId: number, projectId: number) {
  const chunks = [
    {
      chunkId: `seed-${randomUUID()}`,
      content: 'Ensure the AKS ingress controller is patched and uses a managed identity for Azure resources.',
      startLine: 5,
      endLine: 10
    },
    {
      chunkId: `seed-${randomUUID()}`,
      content: 'Enable Datadog logs injection alongside dd-trace to correlate errors with distributed traces.',
      startLine: 12,
      endLine: 18
    },
    {
      chunkId: `seed-${randomUUID()}`,
      content: 'Queue worker retries should back off exponentially and emit telemetry to the monitoring pipeline.',
      startLine: 20,
      endLine: 28
    }
  ]

  await prisma.$executeRawUnsafe(`
    DELETE FROM rag_chunks WHERE metadata ->> 'seedSource' = 'seed-document-embeddings'
  `)

  for (const chunk of chunks) {
    const embeddingLiteral = generateVectorLiteral()
    const metadata = {
      seedSource: 'seed-document-embeddings',
      workspaceId,
      projectId,
      tags: ['demo', 'vector-seed']
    }

    const insertSql = `
      INSERT INTO rag_chunks (
        file_id, chunk_id, content, start_line, end_line, tokens,
        embedding, metadata, created_at
      ) VALUES (
        ${fileId},
        ${sqlString(chunk.chunkId)},
        ${sqlString(chunk.content)},
        ${chunk.startLine},
        ${chunk.endLine},
        ${estimateTokens(chunk.content)},
        '${embeddingLiteral}'::vector,
        ${sqlString(JSON.stringify(metadata))}::jsonb,
        NOW()
      )
      ON CONFLICT (chunk_id) DO UPDATE SET
        content = EXCLUDED.content,
        start_line = EXCLUDED.start_line,
        end_line = EXCLUDED.end_line,
        tokens = EXCLUDED.tokens,
        embedding = EXCLUDED.embedding,
        metadata = EXCLUDED.metadata;
    `

    await prisma.$executeRawUnsafe(insertSql)
  }

  const [{ chunk_count }] = await prisma.$queryRaw<Array<{ chunk_count: number }>>`
    SELECT COUNT(*)::int AS chunk_count
    FROM rag_chunks
    WHERE metadata ->> 'seedSource' = 'seed-document-embeddings'
  `

  return chunk_count
}

async function main() {
  const start = Date.now()
  await ensureVectorSchema()
  const { file, workspace, project } = await seedRelationalScaffold()
  const totalDocs = await seedDocumentEmbeddings()
  const totalChunks = await seedRagChunks(file.id, workspace.id, project.id)

  const duration = Date.now() - start
  console.log('✅ Seed complete')
  console.log(`   • document_embeddings rows: ${totalDocs}`)
  console.log(`   • seeded rag_chunks rows : ${totalChunks}`)
  console.log(`   • workspace ID          : ${workspace.workspace_id}`)
  console.log(`   • duration              : ${duration}ms`)
}

main()
  .catch((error) => {
    console.error('❌ Seed script failed:', error)
    process.exitCode = 1
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
