#!/bin/bash

# Datadog Log Aggregation
source "$(dirname "$0")/lib/log-aggregation.sh"

# Web Testing Workflows Validation Script
# Generated by Agent 3 - Quality Engineer
# Date: 2025-10-02

# Initialize log aggregation
init_log_aggregation


set -e

echo "=================================================="
echo "Web Testing Workflows Validation"
echo "=================================================="
echo ""

# Color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Validation counters
PASS=0
FAIL=0
WARN=0

validate_file() {
    local file=$1
    local description=$2

    if [ -f "$file" ]; then
        echo -e "${GREEN}✅${NC} $description: $file"
        ((PASS++))
        return 0
    else
        echo -e "${RED}❌${NC} $description: $file"
        ((FAIL++))
        return 1
    fi
}

validate_content() {
    local file=$1
    local pattern=$2
    local description=$3

    if grep -q "$pattern" "$file" 2>/dev/null; then
        echo -e "${GREEN}✅${NC} $description"
        ((PASS++))
        return 0
    else
        echo -e "${RED}❌${NC} $description"
        ((FAIL++))
        return 1
    fi
}

warn_if_missing() {
    local file=$1
    local pattern=$2
    local description=$3

    if ! grep -q "$pattern" "$file" 2>/dev/null; then
        echo -e "${YELLOW}⚠️${NC}  $description"
        ((WARN++))
    fi
}

echo "1. Checking Workflow Files"
echo "----------------------------"
validate_file ".github/workflows/test-coverage.yml" "Coverage workflow"
validate_file ".github/workflows/test-simple.yml" "Simple test workflow"
validate_file ".github/workflows/test-amd64-web.yml" "AMD64 Docker workflow"
validate_file ".github/workflows/test-arm64-web.yml" "ARM64 Docker workflow"
echo ""

echo "2. Checking Playwright Configuration"
echo "-------------------------------------"
validate_file "playwright.config.ts" "Playwright config"
validate_content "playwright.config.ts" "testDir: './tests/e2e'" "Playwright test directory configured"
validate_content "playwright.config.ts" "baseURL.*localhost:3000" "Playwright base URL configured"
echo ""

echo "3. Checking Jest Configuration"
echo "-------------------------------"
validate_file "jest.config.js" "Jest config"
validate_content "jest.config.js" "testEnvironment.*jsdom" "Jest DOM environment configured"
validate_content "jest.config.js" "coverageDirectory.*coverage" "Jest coverage directory configured"
echo ""

echo "4. Checking E2E Test Files"
echo "---------------------------"
validate_file "tests/e2e/simple-test.spec.ts" "Simple test file"
validate_file "tests/e2e/health-check.spec.ts" "Health check test file"
echo ""

echo "5. Validating test-coverage.yml Content"
echo "----------------------------------------"
validate_content ".github/workflows/test-coverage.yml" "npx playwright install" "Playwright browser installation"
validate_content ".github/workflows/test-coverage.yml" "e2e-coverage" "E2E coverage job exists"
validate_content ".github/workflows/test-coverage.yml" "coverage-report" "Coverage report job exists"
validate_content ".github/workflows/test-coverage.yml" "upload-artifact" "Artifact upload configured"
echo ""

echo "6. Validating test-simple.yml Content"
echo "--------------------------------------"
validate_content ".github/workflows/test-simple.yml" "npx playwright install" "Playwright browser installation"
validate_content ".github/workflows/test-simple.yml" "test-playwright-basic" "Playwright basic test job exists"
validate_content ".github/workflows/test-simple.yml" "browser-compatibility" "Browser compatibility job exists"
validate_content ".github/workflows/test-simple.yml" "matrix:" "Browser matrix configured"
echo ""

echo "7. Checking Package.json Scripts"
echo "---------------------------------"
validate_content "package.json" "test:e2e.*playwright test" "E2E test script"
validate_content "package.json" "test:coverage.*jest --coverage" "Coverage test script"
validate_content "package.json" "@playwright/test" "Playwright dependency"
echo ""

echo "8. Validating Browser Support"
echo "------------------------------"
validate_content ".github/workflows/test-simple.yml" "chromium" "Chromium browser configured"
validate_content ".github/workflows/test-simple.yml" "firefox" "Firefox browser configured"
validate_content ".github/workflows/test-simple.yml" "webkit" "WebKit browser configured"
echo ""

echo "9. Checking Artifact Configuration"
echo "-----------------------------------"
validate_content ".github/workflows/test-coverage.yml" "retention-days: 7" "Coverage artifacts retention"
validate_content ".github/workflows/test-simple.yml" "retention-days: 3" "Simple test artifacts retention"
echo ""

echo "10. Optional Enhancements Check"
echo "--------------------------------"
warn_if_missing "playwright.config.ts" "globalSetup" "Global setup configured (optional)"
warn_if_missing "playwright.config.ts" "globalTeardown" "Global teardown configured (optional)"
warn_if_missing ".github/workflows/test-coverage.yml" "GITHUB_STEP_SUMMARY" "GitHub step summary (recommended)"
echo ""

echo "=================================================="
echo "Validation Summary"
echo "=================================================="
echo -e "${GREEN}Passed:${NC} $PASS"
echo -e "${RED}Failed:${NC} $FAIL"
echo -e "${YELLOW}Warnings:${NC} $WARN"
echo ""

if [ $FAIL -eq 0 ]; then
    echo -e "${GREEN}✅ All critical validations passed!${NC}"
    echo ""
    echo "Next Steps:"
    echo "1. Run: npm run test:e2e to verify Playwright setup"
    echo "2. Run: npm run test:coverage to verify Jest coverage"
    echo "3. Test workflows locally with act (if available)"
    echo "4. Push changes to trigger GitHub Actions"
    exit 0
else
    echo -e "${RED}❌ Some validations failed. Please review the issues above.${NC}"
    exit 1
fi
