/**
 * Interface for embedding service implementations
 */

import { logger } from '../logger';

export interface EmbeddingService {
  /**
   * Generates embeddings for a single text input
   * @param text The text to generate embeddings for
   * @returns A vector embedding as an array of numbers
   */
  generateEmbedding(text: string): Promise<number[]>;
  
  /**
   * Generates embeddings for multiple text inputs
   * @param texts An array of texts to generate embeddings for
   * @returns An array of vector embeddings
   */
  generateEmbeddings(texts: string[]): Promise<number[][]>;
  
  /**
   * Gets the dimension of the embeddings generated by this service
   * @returns The embedding dimension
   */
  getDimension(): number;
  
  /**
   * Gets the name of the model used for embeddings
   * @returns The model name
   */
  getModelName(): string;
  
  /**
   * Performs a health check on the embedding service
   * @returns True if the service is healthy
   */
  healthCheck(): Promise<boolean>;
}

/**
 * Configuration for embedding services
 */
export interface EmbeddingServiceConfig {
  apiKey?: string;
  endpoint?: string;
  model?: string;
  dimensions?: number;
  timeout?: number;
  maxBatchSize?: number;
  concurrentRequests?: number;
  retryAttempts?: number;
  retryDelay?: number;
  useCache?: boolean;
  cacheTtl?: number;
  customHeaders?: Record<string, string>;
  database?: {
    host: string;
    port: number;
    user: string;
    password: string;
    database: string;
    tableName: string;
    useConnectionPool: boolean;
  };
}

/**
 * Factory for creating embedding service instances
 */
export class EmbeddingServiceFactory {
  /**
   * Creates an embedding service based on the configuration
   * @param config The configuration for the embedding service
   * @returns An embedding service instance
   */
  static create(config: EmbeddingServiceConfig): EmbeddingService {
    // Return MockEmbeddingService as fallback
    return new MockEmbeddingService(config);
  }
}

/**
 * Base class for embedding services with common functionality
 */
export abstract class BaseEmbeddingService implements EmbeddingService {
  protected readonly config: EmbeddingServiceConfig;
  protected readonly modelName: string;
  protected readonly dimensions: number;
  
  /**
   * Creates a new base embedding service
   * @param config The configuration for the embedding service
   */
  constructor(config: EmbeddingServiceConfig) {
    this.config = {
      timeout: 30000,
      maxBatchSize: 20,
      concurrentRequests: 5,
      retryAttempts: 3,
      retryDelay: 1000,
      useCache: true,
      cacheTtl: 86400, // 24 hours
      ...config
    };
    
    this.modelName = this.config.model || 'default';
    this.dimensions = this.config.dimensions || 1536; // Default to OpenAI dimensions
  }
  
  /**
   * Gets the dimension of the embeddings generated by this service
   * @returns The embedding dimension
   */
  getDimension(): number {
    return this.dimensions;
  }
  
  /**
   * Gets the name of the model used for embeddings
   * @returns The model name
   */
  getModelName(): string {
    return this.modelName;
  }
  
  /**
   * Generates embeddings for a single text input
   * @param text The text to generate embeddings for
   * @returns A vector embedding as an array of numbers
   */
  abstract generateEmbedding(text: string): Promise<number[]>;
  
  /**
   * Generates embeddings for multiple text inputs
   * Default implementation just calls generateEmbedding for each text
   * Subclasses should override this with batch API calls when available
   * @param texts An array of texts to generate embeddings for
   * @returns An array of vector embeddings
   */
  async generateEmbeddings(texts: string[]): Promise<number[][]> {
    // Process in batches to avoid overwhelming the API
    const batchSize = this.config.maxBatchSize || 20;
    const batches: string[][] = [];

    // Split texts into batches
    for (let i = 0; i < texts.length; i += batchSize) {
      batches.push(texts.slice(i, i + batchSize));
    }
    
    // Process each batch with limited concurrency
    const results: number[][] = [];
    
    for (const batch of batches) {
      // Process this batch concurrently
      const batchResults = await Promise.all(
        batch.map(text => this.generateEmbedding(text))
      );
      
      results.push(...batchResults);
    }
    
    return results;
  }
  
  /**
   * Performs a health check on the embedding service
   * @returns True if the service is healthy
   */
  async healthCheck(): Promise<boolean> {
    try {
      // Try to generate an embedding for a simple text
      const embedding = await this.generateEmbedding("health check");
      
      // Check if the embedding has the expected dimensions
      return Array.isArray(embedding) && embedding.length === this.dimensions;
    } catch (error) {
      logger.error("Embedding service health check failed:", { error: error });
      return false;
    }
  }
}

/**
 * Simple in-memory embedding service for testing
 */
export class MockEmbeddingService extends BaseEmbeddingService {
  /**
   * Creates a mock embedding service
   * @param config Configuration options
   */
  constructor(config: EmbeddingServiceConfig = {}) {
    super({
      model: 'mock-embedding-model',
      dimensions: config.dimensions || 384,
      ...config
    });
  }
  
  /**
   * Generates a deterministic mock embedding for a text
   * @param text The text to generate an embedding for
   * @returns A mock embedding vector
   */
  async generateEmbedding(text: string): Promise<number[]> {
    // Create a deterministic embedding based on the text
    const hash = this.simpleHash(text);
    const embedding: number[] = [];
    
    // Generate a deterministic vector using the hash
    for (let i = 0; i < this.dimensions; i++) {
      // Use a simple algorithm to generate a number between -1 and 1
      const value = Math.sin((hash + i) * 0.1) * 0.5;
      embedding.push(value);
    }
    
    // Normalize the vector to have length 1
    const length = Math.sqrt(embedding.reduce((sum, val) => sum + val * val, 0));
    return embedding.map(val => val / length);
  }
  
  /**
   * Calculates a simple hash code for a string
   * @param str The string to hash
   * @returns A numeric hash code
   */
  private simpleHash(str: string): number {
    let hash = 0;
    
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32bit integer
    }
    
    return Math.abs(hash);
  }
}