datadog:
  apiKey: "c04039be840f88be08fb15e81f9b3e61"
  site: datadoghq.com
  clusterName: local-tundra-dome
  apm:
    portEnabled: true
  logs:
    enabled: true
    containerCollectAll: true
  kubelet:
    tlsVerify: false
agents:
  containers:
    agent:
      env:
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
clusterAgent:
  enabled: true
