name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Configure Datadog Test Optimization
      uses: datadog/test-visibility-github-action@v2
      with:
        languages: js
        dd_api_key: ${{secrets.DD_API_KEY}}
        site: datadoghq.com

    - name: Run tests
      run: npm test
      env:
        NODE_OPTIONS: -r ${{env.DD_TRACE_PACKAGE}}

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Build application
      run: npm run build

    - name: Run Playwright tests
      run: npm run test:e2e
      env:
        NODE_OPTIONS: -r ${{env.DD_TRACE_PACKAGE}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Main App Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.production
        push: false
        tags: vibecode/webgui:ci-latest

    - name: Build WPA Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./watermarkpodautoscaler
        file: ./watermarkpodautoscaler/Dockerfile
        push: false
        tags: vibecode/wpa:ci-latest

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0

    - name: Run npm audit
      run: npm audit --audit-level=high
      
    - name: Run license check
      run: |
        npm install -g license-checker
        ./scripts/check-licenses.sh

    - name: Datadog SAST Scan
      if: github.event_name == 'push'
      run: npx @datadog/datadog-ci@2.29.0 sast scan
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_APP_KEY: ${{ secrets.DD_APP_KEY }}

    - name: Generate SBOM for SCA
      run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json

    - name: Datadog SCA Scan
      if: github.event_name == 'push'
      run: npx @datadog/datadog-ci@2.29.0 sbom upload sbom.json
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_APP_KEY: ${{ secrets.DD_APP_KEY }}