name: VibeCode CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps --omit=optional

      - name: Clean platform-specific dependencies
        run: |
          # Remove platform-specific Next.js dependencies that might cause issues
          rm -rf node_modules/@next/swc-darwin-*
          rm -rf node_modules/@next/swc-linux-*
          rm -rf node_modules/@next/swc-win32-*
          # Reinstall only the current platform's dependencies
          npm install --legacy-peer-deps --omit=optional

      - name: Lint code
        run: npm run lint

      - name: Check types
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
