name: VibeCode CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Remove platform-specific dependencies for CI
          npm pkg delete devDependencies.@next/swc-darwin-arm64
          npm pkg delete devDependencies.@next/swc-darwin-x64
          npm pkg delete devDependencies.@next/swc-linux-arm64-gnu
          npm pkg delete devDependencies.@next/swc-linux-arm64-musl
          npm pkg delete devDependencies.@next/swc-linux-x64-gnu
          npm pkg delete devDependencies.@next/swc-linux-x64-musl
          npm pkg delete devDependencies.@next/swc-win32-arm64-msvc
          npm pkg delete devDependencies.@next/swc-win32-ia32-msvc
          npm pkg delete devDependencies.@next/swc-win32-x64-msvc
          npm ci --legacy-peer-deps --omit=optional

      - name: Lint code
        run: npm run lint

      - name: Check types
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build
