name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'content/wiki/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:
    inputs:
      docs_system:
        description: 'Which documentation system to deploy'
        required: true
        default: 'astro'
        type: choice
        options:
          - astro
          - nextjs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      # --- Astro Build Steps ---
      - name: Setup Node.js for Astro
        if: "github.event_name == 'push' || github.event.inputs.docs_system == 'astro'"
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './docs/package-lock.json'

      - name: Install Astro dependencies
        if: "github.event_name == 'push' || github.event.inputs.docs_system == 'astro'"
        run: npm ci
        working-directory: ./docs

      - name: Build Astro site
        if: "github.event_name == 'push' || github.event.inputs.docs_system == 'astro'"
        run: npm run build
        working-directory: ./docs

      - name: Upload Astro artifact
        if: "github.event_name == 'push' || github.event.inputs.docs_system == 'astro'"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

      # --- Next.js Build Steps ---
      - name: Setup Node.js for Next.js
        if: "github.event.inputs.docs_system == 'nextjs'"
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install Next.js dependencies
        if: "github.event.inputs.docs_system == 'nextjs'"
        run: npm ci

      - name: Build Next.js site
        if: "github.event.inputs.docs_system == 'nextjs'"
        run: npm run build

      - name: Upload Next.js artifact
        if: "github.event.inputs.docs_system == 'nextjs'"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4