name: Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_BASE64 }}

      - name: Deploy VibeCode Application
        run: |
          chmod +x ./scripts/production-deploy.sh
          ./scripts/production-deploy.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Deploy Monitoring Stack
        run: |
          chmod +x ./scripts/deploy-monitoring.sh
          ./scripts/deploy-monitoring.sh -m kubernetes
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
