name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775199f52540f319c9545d6164b4 # v4.0.3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level=high
      
    - name: Run license check
      run: |
        npm install -g license-checker
        ./scripts/check-licenses.sh

    - name: Generate SBOM for SCA
      run: npx @cyclonedx/bom@3.11.0 --output sbom.json

    - name: Datadog SCA Scan
      if: github.event_name == 'push'
      run: npx @datadog/datadog-ci@2.29.0 sbom upload sbom.json
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_APP_KEY: ${{ secrets.DD_APP_KEY }}

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: Initialize CodeQL
      uses: github/codeql-action/init@b6115784655dacb0d61a442b85a3598cd7589578 # v2.22.11
      with:
        languages: javascript
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@b6115784655dacb0d61a442b85a3598cd7589578 # v2.22.11

    - name: Upload CodeQL SARIF to Datadog
      if: github.event_name == 'push'
      run: npx @datadog/datadog-ci@2.29.0 sarif upload ./results/codeql.sarif
      env:
        DD_API_KEY: ${{ secrets.DD_API_KEY }}
        DD_APP_KEY: ${{ secrets.DD_APP_KEY }}