name: Run Synthetic Tests

on:
  workflow_dispatch:

jobs:
  run-synthetic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Remove platform-specific dependencies for CI
          npm pkg delete devDependencies.@next/swc-darwin-arm64 2>/dev/null || true
          npm ci --legacy-peer-deps --omit=optional

      - name: Run Datadog Synthetic Tests
        run: |
          datadog-ci synthetics run-tests --search "VibeCode Critical User Journey" --failOnCriticalErrors
        env:
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
          DATADOG_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DATADOG_SITE: datadoghq.com
